import Head from "next/head";
import Transactions from "../components/Transactions";

const Account = () => {

  return (
    <div>
      <Head>
        <title>NG.Cash | Account</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Transactions />
    </div>
  );
}

export default Account;
