import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";
import { getUsers } from "../fetchs/fetchs";
import IUser from "../interfaces/IUser";

const Account = () => {
  const [users, setUsers] = useState<IUser[]>();
  const [userLogged, setUserLogged] = useState<IUser>();

  
  useEffect( () => {
    getUsers().then(res => setUsers(res));
    const username = localStorage.getItem('username');
    const findUser: IUser | undefined = users?.find((user: {
      username: string | undefined, password: string | undefined
    }) => user.username === username);
    console.log(findUser?.account.balance);
    
    setUserLogged(findUser);
  }, []);
  return (
    <div>
      <Head>
        <title>NG.Cash | Account</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <div className="flex justify-between items-center border-b-[1px] py-4">
          <p className="text-lg">Olá, {userLogged?.username}!</p>
          <Image src="/logo-ngcash.svg" width={90} height={90} alt="ng Logo" />
          <div className="flex flex-col justify-between items-center h-14">
            <p>Saldo: <span>R$ {userLogged && userLogged.account.balance}</span></p>
            <Link href="/"><p className="ml-4 bg-gradient-to-br from-gray-400 to-gray-600 text-white font-bold px-4 rounded hover:bg-gradient-to-br hover:from-gray-500 hover:to-gray-700">Sair</p></Link>
          </div>
        </div>
      </header>
      <main>
        <section>
          <h1>Histórico</h1>
          <table>
        <thead>
          <tr>
            <th>Nome</th>
            <th>Sobrenome</th>
            <th>Email</th>
          </tr>
        </thead>
        <tbody>
          {users?.map((user) => (
            <tr key={ user.id }>
              <td>{user.username}</td>
              <td>{user.accountId}</td>
              <td>20/12/1992</td>
            </tr>
          ))}
        </tbody>
      </table>
        </section>
      </main>
    </div>
  );
}

export default Account;
