import Head from 'next/head'
import Image from 'next/image'
export default function Home() {
  return (
    <div>
      <Head>
        <title>NG.Cash</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <ul>
          <li><Image src="/logo-ngcash.svg" width={60} height={60} alt="ng Logo" /></li>
        </ul>
      </header>
      <h1 className='font-poppins'>LOGIN</h1>
    </div>
  )
}
